# Generated by Django 4.2.4 on 2023-08-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigi_burger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
